"""Provenance tests for the instances shipped in ``Data/``.

Reviewer-facing purpose: every number in ``Data/`` that was *imposed by the
authors* rather than taken from a published source must be reproducible from
a rule stated in the manuscript.  These tests execute the two derivation
scripts in ``Data/design/`` and require them to reproduce the committed
instance files exactly.

* ``Data/design/build_gone_abat_jap_capacities.py`` re-derives all 560
  conveyance capacities and all 16 source allocations of the Gone Abat Jap
  instance from the rules of Appendix A.4, using only the published topology,
  efficiencies and demands (Mendeley Data, doi:10.17632/xt3gsf89n9.1).
* ``Data/design/build_synthetic_scale.py`` regenerates the whole synthetic
  scale instance from its closed construction rule, with no random number
  generator anywhere.
"""

from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
DESIGN_DIR = REPO_ROOT / "Data" / "design"
GONE_ABAT_JAP = REPO_ROOT / "Data" / "benchmarks" / "gone_abat_jap.json"
SYNTHETIC_SCALE = REPO_ROOT / "Data" / "synthetic_scale_500u_1022e_4p.json"


def _load(script_name: str):
    path = DESIGN_DIR / script_name
    spec = importlib.util.spec_from_file_location(path.stem, path)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[path.stem] = module
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="module")
def gone_abat_jap_builder():
    return _load("build_gone_abat_jap_capacities.py")


@pytest.fixture(scope="module")
def synthetic_builder():
    return _load("build_synthetic_scale.py")


def test_gone_abat_jap_capacities_follow_the_stated_rule(gone_abat_jap_builder):
    """All 560 conveyance capacities follow the Appendix A.4 rule exactly."""
    module = gone_abat_jap_builder
    data = json.loads(GONE_ABAT_JAP.read_text(encoding="utf-8"))
    derived = module.derive_capacities(data)
    diffs = module.compare(data, derived)
    assert diffs == [], f"{len(diffs)} capacity value(s) deviate from the A.4 rule: {diffs[:5]}"


def test_gone_abat_jap_source_allocations_follow_the_stated_rule(
        gone_abat_jap_builder):
    """All 16 source allocations follow the Appendix A.4 rule exactly.

    They are imposed by the authors, not published, which is what makes the
    scenario a controlled scarcity scenario; Data/README.md says so.
    """
    module = gone_abat_jap_builder
    data = json.loads(GONE_ABAT_JAP.read_text(encoding="utf-8"))
    derived = module.derive_source_capacity(data)
    diffs = module.compare_source(data, derived)
    assert diffs == [], f"{len(diffs)} source allocation(s) deviate: {diffs[:5]}"


def test_data_readme_calls_the_source_allocations_imposed():
    """The provenance statement of Data/README.md matches the derivation."""
    readme = (REPO_ROOT / "Data" / "README.md").read_text(encoding="utf-8")
    published, imposed = readme.split("### 3.2 Imposed parameters", maxsplit=1)
    assert "source_capacity" not in published.split("### 3.1", maxsplit=1)[1]
    assert "source_capacity" in imposed


def test_gone_abat_jap_scarcity_structure(gone_abat_jap_builder):
    """Exactly nine (reach, period) pairs are binding, each at 9/10 of the load."""
    from fractions import Fraction

    module = gone_abat_jap_builder
    data = json.loads(GONE_ABAT_JAP.read_text(encoding="utf-8"))
    loads = module.full_supply_loads(data)
    capacities = data["edge_capacity"]

    binding = []
    slack_ratios = []
    for period in data["periods"]:
        for edge in data["edges"]:
            load = loads[(edge["id"], period)]
            if load == 0:
                continue
            ratio = Fraction(capacities[period][edge["id"]]) / load
            if ratio < 1:
                binding.append((edge["id"], period))
            else:
                slack_ratios.append(ratio)

    assert sorted(binding) == sorted(module.SCARCITY_PAIRS)
    assert len(binding) == 9
    # Outside the nine imposed pairs no reach is tighter than 1.05 of its load.
    assert min(slack_ratios) >= Fraction(21, 20) - Fraction(1, 10**6)


def test_synthetic_scale_instance_is_reproducible_bit_for_bit(synthetic_builder):
    """The synthetic scale instance is regenerated byte-for-byte from its rule."""
    module = synthetic_builder
    generated = module.render(module.build())
    stored = SYNTHETIC_SCALE.read_text(encoding="utf-8")
    assert generated == stored


def test_data_readme_lists_every_instance_file():
    """Data/README.md documents the provenance of every instance shipped."""
    readme = (REPO_ROOT / "Data" / "README.md").read_text(encoding="utf-8")
    instances = sorted(p for p in (REPO_ROOT / "Data").rglob("*.json"))
    assert instances, "no instance files found under Data/"
    missing = [p.name for p in instances if p.name not in readme]
    assert missing == [], f"Data/README.md does not mention: {missing}"
