"""Tests for the inverse-design publication assets.

Two things must hold for the conference paper and the journal article to stay
independent:

* ``generate_results`` must not delete ``results/investment`` and must not
  hash it into the article's run manifest;
* ``generate_investment_results`` must be deterministic, so the numbers in
  the paper can be regenerated byte for byte.
"""

from __future__ import annotations

import hashlib
import json
import shutil
from fractions import Fraction
from pathlib import Path

import pandas as pd
import pytest

from appliedmath_lexflow.investment_reporting import generate_investment_results
from appliedmath_lexflow.reporting import generate_results

ROOT = Path(__file__).resolve().parents[1]
SOURCE_DATA = ROOT / "Data" / "benchmarks"
SOURCE_DESIGN = ROOT / "Data" / "design"

EXPECTED_FILES = (
    "INVESTMENT_SUMMARY.json",
    "run_manifest.json",
    "tables/csv/table_1_investment_plans.csv",
    "tables/csv/table_2_critical_resources.csv",
    "tables/excel/table_1_investment_plans.xlsx",
    "tables/excel/table_2_critical_resources.xlsx",
    "figure_data/csv/figure_1_greedy_lining_trap.csv",
    "figure_data/csv/figure_2_guarantee_budget_curves.csv",
    "figure_data/csv/figure_3_headroom_map.csv",
    "figures/figure_1_greedy_lining_trap.png",
    "figures/figure_2_guarantee_budget_curves.png",
    "figures/figure_3_headroom_map.png",
)


@pytest.fixture(scope="module")
def workspace(tmp_path_factory) -> Path:
    """A throwaway project tree holding only the inputs the pipelines read."""
    root = tmp_path_factory.mktemp("investment")
    data_dir = root / "Data" / "benchmarks"
    design_dir = root / "Data" / "design"
    data_dir.mkdir(parents=True)
    design_dir.mkdir(parents=True)
    for source in SOURCE_DATA.glob("*.json"):
        shutil.copy2(source, data_dir / source.name)
    for source in SOURCE_DESIGN.glob("*.json"):
        shutil.copy2(source, design_dir / source.name)
    generate_investment_results(root)
    return root


def _hashes(root: Path) -> dict[str, str]:
    return {
        str(path.relative_to(root)): hashlib.sha256(path.read_bytes()).hexdigest()
        for path in sorted((root / "results" / "investment").rglob("*"))
        if path.is_file() and path.name != "run_manifest.json"
    }


def test_every_expected_asset_is_written(workspace: Path) -> None:
    base = workspace / "results" / "investment"
    for relative in EXPECTED_FILES:
        path = base / relative
        assert path.is_file(), relative
        assert path.stat().st_size > 0, relative


def test_generated_assets_are_byte_reproducible(workspace: Path) -> None:
    first = _hashes(workspace)
    generate_investment_results(workspace)
    assert _hashes(workspace) == first


def test_summary_records_the_headline_findings(workspace: Path) -> None:
    summary = json.loads(
        (workspace / "results" / "investment" / "INVESTMENT_SUMMARY.json").read_text(
            encoding="utf-8"
        )
    )
    assert summary["reference_instance"] == "gone_abat_jap"
    assert summary["resources_m"] == 548
    assert summary["critical_resources"] == 18
    assert summary["near_tied_bottleneck_set_1e_9"] == 7
    assert round(summary["widening_only_full_service_cost"]) == 1176721
    assert 0.44 < summary["mixed_plan_savings"]["0.90"] < 0.45
    counterexample = summary["counterexample"]
    assert counterexample["lambda_star_before"] == "1/2"
    assert counterexample["lambda_star_after_joint_step"] == "1"
    assert counterexample["single_edge_gain"] == 0.0
    assert counterexample["transversal_is_exact"] is True


def test_plan_table_covers_every_benchmark_and_strategy(workspace: Path) -> None:
    frame = pd.read_csv(
        workspace / "results" / "investment" / "tables" / "csv" / "table_1_investment_plans.csv"
    )
    assert frame["benchmark"].nunique() == 6
    assert set(frame["strategy"]) == {"widening", "lining_then_widening"}
    # Lining first can never require more capacity than widening alone.
    assert (frame["saving_vs_widening_only"] >= 0).all()
    assert (frame["upgraded_resources"] <= frame["total_resources"]).all()


def test_curve_source_data_is_convex_per_scenario(workspace: Path) -> None:
    frame = pd.read_csv(
        workspace
        / "results"
        / "investment"
        / "figure_data"
        / "csv"
        / "figure_2_guarantee_budget_curves.csv"
    )
    for _, part in frame.groupby("scenario"):
        ordered = part.sort_values("tau_low")
        assert ordered["marginal_cost"].is_monotonic_increasing
        assert ordered["funded_resources"].is_monotonic_increasing
        assert ordered["budget_at_tau_low"].is_monotonic_increasing


def test_article_pipeline_preserves_and_ignores_the_investment_folder(
    workspace: Path,
) -> None:
    """The two reporting guards, checked together on a real article run."""
    investment = workspace / "results" / "investment"
    before = _hashes(workspace)
    assert before

    generate_results(workspace)

    assert investment.is_dir(), "the article run deleted the conference assets"
    assert _hashes(workspace) == before, "the article run overwrote them"

    manifest = json.loads(
        (workspace / "results" / "manifests" / "run_manifest.json").read_text(
            encoding="utf-8"
        )
    )
    assert manifest["result_files"], "the article manifest should not be empty"
    assert not [
        name for name in manifest["result_files"] if "investment" in name
    ], "conference assets leaked into the article provenance record"


def test_design_instance_is_not_an_article_benchmark(workspace: Path) -> None:
    """``Data/design`` must stay outside the benchmark family of the article."""
    manifest = json.loads(
        (workspace / "results" / "manifests" / "run_manifest.json").read_text(
            encoding="utf-8"
        )
    )
    assert len(manifest["benchmark_hashes"]) == 6
    assert "greedy_lining_trap.json" not in manifest["benchmark_hashes"]


def test_investment_manifest_records_its_own_inputs(workspace: Path) -> None:
    manifest = json.loads(
        (workspace / "results" / "investment" / "run_manifest.json").read_text(
            encoding="utf-8"
        )
    )
    assert "greedy_lining_trap.json" in manifest["inputs"]
    assert "gone_abat_jap.json" in manifest["inputs"]
    assert len(manifest["inputs"]) == 7  # six benchmarks plus the design instance
    assert all("investment" in name for name in manifest["outputs"])
